/** Localisation */

i18n.map('ru', {
        siteName: 'BankerBurg',
        connectToServer: 'Соединено с сервером',
        notConnectToServer: 'Соединено с сервером отсутствует',
        goScoring: 'Пройти Скоринг',
        createProject: 'Создать проект',
        createIssue: 'Создать вопрос',
        listOfQuestions: 'Список вопросов',
        listOfProjects: 'Список проектов',
        answerTheQuestionsMakingBankLoan:'Ответьте на вопросы для принятия банком решения о выдаче кредита:',
        clickOnLinksYouRequirePassScoring:'Кликните по одной из ссылок для прохождения нужного вам скоринга:',
        toHome:'На главную',
        next:'Дальше',
        form:{
            answersForScoring: 'Вопросы для скоринга:',
            typeOfDisplay: 'Тип отображения:',
            deleteConfirm: 'Вы уверены что хотите удалить?'
        },
        title:'Название',
		bankName: 'Название банка',
        control: 'Управление',
        listing:'Листинг',
        autoload:'Автозагрузка',
        question:"Вопрос:",
        selectQuestion: 'Выбрать вопрос:',
        scoringType: 'Тип скоринга:',
        relScoringPage: 'Относительный адрес страницы скоринга:',
        questionStruct: 'Структура вопросов:',
        commentsForPoints: 'Комментарии для диапазона баллов:',
        from: 'От:',
		sumFrom: 'Сумма от:',
        before: 'До:',
        commentForRange: 'Комментарий для диапазона:',
        commentForAdmin: 'Комментарий для администратора:',
        answers: 'Ответы:',
        textAnswer: 'Текст ответа:',
        point: 'Балл:',
        totalPoints: 'Общий балл:',
        resCount: 'Результат подсчета:',
        name: 'Имя:',
        surname: 'Фамилия:',
        phone: 'Телефон:',
        projectName: 'Проект скоринга:',
        resultComment: 'Комментарий результата:',
        save: 'Сохранить',
		country: 'Страна',
		countryes: 'Страны',
		bankList: 'Список банков',
		addBank: 'Добавить банк',
		currency: 'Валюта',
		deposits: 'Вклады',
		rub: 'Рубль',
		usd: 'Доллар США',
		euro: 'Евро',
		cny: 'Китайский юань',
		rates: 'Ставки',
		time2percent: 'Срок / Ставка %',
		ratePercent: 'Ставка %',
		payPercent: 'Выплата процентов',
		inEndOfTerm: 'В конце срока',
		monthly: 'Ежемесячно',
		dayly: 'Ежедневно',
		capitalization: 'Капитализация',
		specialDepo: 'Специальный вклад',
		comment: 'Комментарий',
		added: 'Пополняемый',
		urlName: 'Идентификатор банка (Латинские симв.)',
		description: 'Описание',
		phones: 'Телефоны',
		linkToBank: 'Ссылка на сайт банка',
		general: 'Общий',
		addresses: 'Адреса',
		address: 'Адрес',
		city: 'Город (регион)',
		bankAddressesList: 'Список адресов банков',
		cityList: 'Список городов',
		addBankAddresses: 'Добавить адрес банка',
		regionAddresses: 'Адреса в регионе',
		bankDepositList: 'Список банковских вкладов',
		addBankDeposit: 'Добавить банковский вклад',
		countryList: 'Список стран',
		
		
        test:'Тест'
    });

i18n.map('en', {
        siteName: 'BankerBurg',
        connectToServer: 'Connect To Server',
        notConnectToServer: 'The connection to the server is offline',
        goScoring: 'Go scoring',
        createProject: 'Create Project',
        createIssue: 'Create Question',
        listOfQuestions: 'List of Questions',
        listOfProjects: 'List of Projects',
        answerTheQuestionsMakingBankLoan:'Answer the questions for decision-making on the bank loan:',
        clickOnLinksYouRequirePassScoring:'Click on one of the links you require to pass the scoring:',
        toHome:'Home',
        next:'Next',
        form:{
            answersForScoring: 'Answers for scoring:',
            typeOfDisplay: 'Type of Display:',
            deleteConfirm: 'Are you sure you want to delete?'
        },
        title:'Title',		
		bankName: 'Bank name',
        control: 'Control',
        listing:'Listing',
        autoload:'Autoload',
        question:"Question:",
        selectQuestion: 'Select a question:',
        scoringType: 'Type of scoring:',
        relScoringPage: 'Relative address of the page scoring:',
        questionStruct: 'The structure of the questions:',
        commentsForPoints: 'Comments for range points:',
        from: 'From:',
		sumFrom: 'Summ from:',
        before: 'Before:',
        commentForRange: 'Comment for range:',
        commentForAdmin: 'Comments for the administrator:',
        answers:'Answers:',
        textAnswer: 'Text of the answer:',
        point: 'Point:',
        totalPoints: 'Total points:',
        resCount: 'Result Counting:',
        name: 'Name:',
        surname: 'Surname:',
        phone: 'Phone:',
        projectName: 'Project name:',
        resultComment: 'Result comment:',
        save: 'Save',
		country: 'Сountry',
		countryes: 'Сountryes',
		bankList: 'List of banks',
		addBank: 'Add bank',
		currency: 'Currency',
		deposits: 'Deposits',
		rub: 'Ruble',
		usd: 'USD',
		euro: 'Euro',
		cny: 'CNY',
		rates: 'Rates',		
		time2percent: 'Term / Rate %',
		ratePercent: 'Rate %',
		payPercent: 'Pay percents',
		inEndOfTerm: 'In end of term',
		monthly: 'Monthly',
		dayly: 'Dayly',
		capitalization: 'Capitalization',
		specialDepo: 'Special deposit',
		comment: 'Comment',		
		added: 'Added',
		urlName: 'Url name',
		description: 'Description',
		phones: 'Phones',
		linkToBank: 'Link to the website of the bank',
		general: 'General',
		addresses: 'Addresses',
		address: 'Address',
		city: 'City (region)',
		bankAddressesList: 'Bank adresses list',
		cityList: 'City list',
		addBankAddresses: 'Add bank address',
		regionAddresses: 'Region addresses',
		bankDepositList: 'List of bank deposits',
		addBankDeposit: 'Add a bank deposit',
		countryList: 'List of countries',
		
			
        test:'Test'
    });
